### ISSUE TITLE
data from China

### ISSUE THREAD

**Issue by kangqiwang** [TheEconomist/covid-19-excess-deaths-tracker#24]
I found the data about china from our world in data. but I cant find it from your tacker link. is there any specific reason? or you can't find normal mortality from china? I found a [paper](https://www.bmj.com/content/372/bmj.n415) which have some data, but it is specific in Wuhan.

**Comment by sondreus** [comment]
Hi, 

Because there is no total mortality data from China, we can't track it, but instead have to rely on our excess deaths model: https://www.economist.com/graphic-detail/coronavirus-excess-deaths-estimates

That is also 100% open source, available here, and you can use it to inspect our approach to estimating excess deaths for China and all other countries where total mortality figures are unknown: https://github.com/TheEconomist/covid-19-the-economist-global-excess-deaths-model 

With regards to that paper specifically: I've reached out repeatedly to the authors of that paper for their replication files, and the Chinese government for data on China, with no result. The limited data we in our global excess deaths model for China, for the first 3 months of 2020, is however based on the linked paper, and in particular, its supplemental appendix. However, it is an extrapolation from the Chinese disease monitoring system (like the paper itself), and so not featured here.
