### ISSUE TITLE
Error on estimation of Excess Deaths in Chile

### ISSUE THREAD

**Issue by elaval** [TheEconomist/covid-19-excess-deaths-tracker#3]
First of all, congratulations for your great work!!!

I would like to warn you that there is an important methodological issue with your estimation of expected deaths in countries like Chile.  

While yearly deaths in some developed countries (e.g. England) are relatively stable, in developing countries there is a natural growth of deaths from year to year (total deaths grew 5.9% in Chile form 2015 to 2019).  This implies that a plain 5 year average (2015 to 2019) will **underestimate expected deaths** for 2020 (and **overestimate excess deaths** on 2020)

I am attaching an image with tables **using data that The Economist publishes for Chile** on this repository.  Here you can clearly see that **expected deaths for 2020 are even higher than deaths that actually happened in Chile on 2019!!** 

Another important wrong result associated to this underestimation is a relatively high number of excess deaths (1045 people) for weeks 1 to 9 (**before the outbreak arrived to Chile on March 3**).  
![image](https://user-images.githubusercontent.com/68602/83081905-d84ce500-a04f-11ea-9d5d-c8518b204ba3.png)

I think that the Excess Deaths report is EXTREMELY VALUABLE, and I am strong promoter of the work that the media is doing on this respect (The Economist, Financial Times, New York Times).

Specially to promote (and validate) the work that you guys are doing, I think that it is important to identify & correct methodological problems (and avoid challenges to the credibility of the reports).  I would kindly suggest to adjust the methodology for the estimation of the excess deaths in developing countries, adjusting the yearly deaths according to expected death growth from the respective year to 2020 (before calculating the 5 year average)  

I have made my own estimation for Excess Deaths in Chile using and adjusted 5 year average and you can find all the data and code in this page [https://observablehq.com/@elaval/mortalidad-en-exceso-durante-epidemia-de-coronavirus-en-ch](https://observablehq.com/@elaval/mortalidad-en-exceso-durante-epidemia-de-coronavirus-en-ch). (I am afraid that it is in Spanish)

![image](https://user-images.githubusercontent.com/68602/83082443-84db9680-a051-11ea-8ecc-803ef0f277be.png)

We do know the death growth (without Coronavirus) from 2015 to 2019, the unknown is the expected rate from 2019 to 2020, so I use the average growth from 2019 to 2019 (1.51%) and do a sensibility analysis with rates that go from 0.61% to 2.41% (+/- 1 std deviation)
I do a sensibility analysis for different values of 
![image](https://user-images.githubusercontent.com/68602/83082473-9755d000-a051-11ea-9c9b-ed4e4de75f2d.png)

I would be happy to provide comments / help if needed, but at least I would recommend that you could publish a warning notice that excess deaths could be overestimated for countries that have a natural growth of yearly deaths.

Best wishes,

Ernesto Laval (@elaval on Twitter & Github)

**Comment by martinalvarado4** [comment]
Hi in addition to @elaval.

I took the data of your `expected_deaths` for the 20 firsts weeks of 2020 (for the summary you call `region`='Chile') from the table `output-data/excess-deaths/chile_excess_deaths.csv` and compared it too the historical data of `total_deaths` for the 20 firsts weeks of 2019  from the table `output-data/historical-deaths/chile_weekly_deaths.csv`.
You can see your expected data for 2020 is 18 out of 20 weeks lower that the real data of 2019. With a added difference of -1.378 deaths. This prediction is clearly underestimating the death for 2020 in Chile which as @elaval point have been growing in the last decade (due to population growth).

I would appreciate if you create a new expected value  (By simple regression or other author data). I think there is an excess of death in Chile but your study is clearly overestimating.

![TableResume](https://user-images.githubusercontent.com/20800415/83104850-963f9580-a087-11ea-855a-56d531ddba9f.PNG)

**Comment by sondreus** [comment]
Hi both,

Thank you very much for this input and sorry for the late reply. We have since these comments were made revised our methods, which I believe answer these concerns. (You might also have been in touch with the another maintainer of this repo). Thank you for the kind words, and strong agree on the need to have solid methods on this important issue. Please open another issue if we our methods can be improved.
